### ISSUE TITLE
Backup message - file content.json was not backup wallet: MoneyNetworkW2

### ISSUE THREAD

**Issue by jaros1** [jaros1/Money-Network#360]
MN - full export with W2 and W3. Notification in MN: file content.json was not backup
wallet: MoneyNetworkW2

![screenshot from 2018-04-25 10-00-03](https://user-images.githubusercontent.com/4932088/39233029-83f9bb5c-486f-11e8-9c8c-99b4e5987cff.png)

[w2-127.0.0.1-1524642897413.log](https://github.com/jaros1/Money-Network/files/1946005/w2-127.0.0.1-1524642897413.log)
[w3-127.0.0.1-1524642758352.log](https://github.com/jaros1/Money-Network/files/1946006/w3-127.0.0.1-1524642758352.log)
[mn-127.0.0.1-1524642722424.log](https://github.com/jaros1/Money-Network/files/1946007/mn-127.0.0.1-1524642722424.log)

**Comment by jaros1** [comment]
Note 2 content.json files in request_wallet_backup response!

09:51:07.684 all.js:140087 MoneyNetworkW2Service.process_incoming_message/776: Using group_debug_seq 776 for this receive request_wallet_backup message operation
09:51:07.684 all.js:140095 MoneyNetworkW2Service.process_incoming_message/776: processing inner_path = merged-MoneyNetwork/1PgyTnnACGd1XRdpfiDihgKwYRRnzgz2zh/data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/6f7cecdf76-i.1524642665896 with encrypt2
09:51:07.684 all.js:140096 MoneyNetworkW2Service.process_incoming_message/776: now = 1524642667685, extra = {"optional_file":true,"group_debug_seq":776,"file_info":{"inner_path":"data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/6f7cecdf76-i.1524642665896","uploaded":0,"is_pinned":1,"time_accessed":0,"site_id":6,"is_downloaded":1,"file_id":24855,"peer":1,"time_added":1524642666,"hash_id":51482,"time_downloaded":1524642666,"size":1124},"hub":"1PgyTnnACGd1XRdpfiDihgKwYRRnzgz2zh","hub_type":"user","db_query_at":1524642667642,"fileget_at":1524642667652,"decrypt_at":1524642667684,"modified":1524642666,"fileget":true,"decrypt":true,"send_overhead":1000,"receive_overhead":42,"total_overhead":1042}
09:51:07.685 all.js:140101 MoneyNetworkW2Service.process_incoming_message/776: filename = 6f7cecdf76-i.1524642665896
09:51:07.685 all.js:140106 MoneyNetworkW2Service.process_incoming_message/776: file_timestamp = 1524642665896
09:51:07.685 all.js:140171 MoneyNetworkW2Service.process_incoming_message/776: request = {"msgtype":"request_wallet_backup"}
09:51:07.686 all.js:141414 MoneyNetworkW2Service.process_incoming_message.request_wallet_backup/776: request = {"msgtype":"request_wallet_backup"}

09:51:07.689 all.js:141431 MoneyNetworkW2Service.process_incoming_message.request_wallet_backup.step_4_send_backup_msg/776: response.filenames = ["content.json","content.json","wallet.json"]

**Comment by jaros1** [comment]
Strange. content.json in files object? Changed js code to  prevent two content.json files in backup response.

**Comment by jaros1** [comment]
Test. OK export with W2 and W3:

![screenshot from 2018-04-25 16-12-55](https://user-images.githubusercontent.com/4932088/39251464-a6a037c4-48a3-11e8-9bab-e4119cdb8043.png)

**Comment by jaros1** [comment]
Error in import confirm box. There should be 2 wallets in import. Not 1 wallet!

[127.0.0.1-1524665844921.log](https://github.com/jaros1/Money-Network/files/1947372/127.0.0.1-1524665844921.log)

![screenshot from 2018-04-25 16-15-38](https://user-images.githubusercontent.com/4932088/39252292-a44ae58a-48a5-11e8-9506-a687f086e9d6.png)

**Comment by jaros1** [comment]
Fixed. Simple JS error in expression. Was using = instread of == ...
Tested restore. Check logs.

[w3-127.0.0.1-1524667894665.log](https://github.com/jaros1/Money-Network/files/1947538/w3-127.0.0.1-1524667894665.log)
[w2-127.0.0.1-1524667884017.log](https://github.com/jaros1/Money-Network/files/1947539/w2-127.0.0.1-1524667884017.log)
[mn-127.0.0.1-1524667870906.log](https://github.com/jaros1/Money-Network/files/1947540/mn-127.0.0.1-1524667870906.log)

**Comment by jaros1** [comment]
W2 restore failed:
16:49:46.478 MoneyNetworkAPI.js:2691 MoneyNetworkW2Service.process_incoming_message.restore_wallet_backup.step_6_restore_wallet_json/829: 
error. could not find 1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ. fileWrite cmd will fail
16:49:47.462 MoneyNetworkAPI.js:2691 MoneyNetworkW2Service.process_incoming_message.restore_wallet_backup.step_6_restore_wallet_json/undefined: 
error. could not find 1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ. fileWrite cmd will fail
16:49:47.781 all.js:141560 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at step_5_restore_files (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:141560:63)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:141562:37
    at run_cb (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:2723:36)
step_5_restore_files @ all.js:141560
(anonymous) @ all.js:141562
run_cb @ MoneyNetworkAPI.js:2723
setTimeout (async)
cb2 @ MoneyNetworkAPI.js:2724
ZeroFrame.onMessage @ all.js:27018
(anonymous) @ all.js:26982
postMessage (async)
Wrapper.sendInner @ all.js?rev=3408&lang=en:1472
Wrapper.onMessageWebsocket @ all.js?rev=3408&lang=en:915
(anonymous) @ all.js?rev=3408&lang=en:830
16:50:31.029 MoneyNetworkAPI.js:2507 MoneyNetworkAPILib.z_file_get.is_optional_file: stopped merged-MoneyNetwork/1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ/data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/e46aad1bc3-i.1491382442801 fileGet request. File is not in content.json file merged-MoneyNetwork/1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ/data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/e46aad1bc3-i.1491382442801
16:50:31.029 MoneyNetworkAPI.js:5404 MoneyNetworkAPI.send_message.delete_request z_file_delete callback 1: res = "Delete error: [Errno 2] No such file or directory"

**Comment by jaros1** [comment]
W2 restore exception:
all.js:141560 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at step_5_restore_files (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:141560:63)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:141562:37
    at run_cb (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:2723:36)

todo:
- check send_exception usage in post processing operations (send_mt, start_mt and restore_wallet_backup). Must use report_error (done)
- add exception handling to restore_wallet_backup (done)
- content is an object. use JSON.stringify (todo)
- content can also be a image. See MN userCtrl import (todo)

**Comment by jaros1** [comment]
Test 3. Expects JS exception in post send money post processing. 
Test "ok" but exception in post processing was never reported in UI

MoneyNetworkW2Service.process_incoming_message.send_mt send_response callback/888: todo: cannot use send_exception in post processing. OK response has already been sent to MN
08:12:25.940 all.js:140197 MoneyNetworkW2Service.process_incoming_message.send_mt send_response callback/888: y is not defined
08:12:25.940 all.js:140198 MoneyNetworkW2Service.process_incoming_message.send_mt send_response callback/888:  ReferenceError: y is not defined
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:140546:53
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:140188:29
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:5409:67
    at ZeroFrame.onMessage (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:27018:17)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js:26982:59
08:12:25.941 MoneyNetworkAPI.js:4429 MoneyNetworkAPI.send_message: encrypt2/874: Using group_debug_seq 874 for this send response message operation
08:12:25.941 MoneyNetworkAPI.js:4429 MoneyNetworkAPI.send_message: encrypt2/874: sessionid = gxap1qz72thfwinhp7m6b9lnox4zqx99hx6jmqwlcfttpsln81vyhzythhwl
08:12:25.941 MoneyNetworkAPI.js:4429 MoneyNetworkAPI.send_message: encrypt2/874: request = {"msgtype":"response","error":"send_mt request failed with JS error y is not defined"}
08:12:25.942 MoneyNetworkAPI.js:4429 MoneyNetworkAPI.send_message: encrypt2/874: msgtype = response, subsystem = api, optional = -i
08:12:25.943 MoneyNetworkAPI.js:5185 MoneyNetworkAPI.send_message: calling start_transaction

**Comment by jaros1** [comment]
Fixed W2 exception handling in 3 post processing messages (send_mt, start_mt and restore_wallet_backup).
todo: copy changes to W3

**Comment by jaros1** [comment]
Also fixed in W3

**Comment by jaros1** [comment]
New W2 restore error:

![screenshot from 2018-04-27 18-14-57](https://user-images.githubusercontent.com/4932088/39373207-23a87e44-4a47-11e8-8eb4-a90b82d41be8.png)

[127.0.0.1-1524845808809.log](https://github.com/jaros1/Money-Network/files/1955886/127.0.0.1-1524845808809.log)

Problem with reading merged-MoneyNetwork/1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ/data/users/1MirY1KnJK3MKzgZiyZZM8FkyzHRJgmMh8/e1af7946c6.0000000000000
fileGet operation started 18:13:06.923. exception at 18:14:07.794. maybe MoneyNetworkAPILib.clear_all_data() call doing w2 restore process?
Added console.log(pgm + 'clearing all MoneyNetworkAPI data. Expect some following JS errors!')

**Comment by jaros1** [comment]
Maybe OK restore in W2. But W2 was not reloaded correct. Escaping from iframe and gray page
w2 before reload: [127.0.0.1-1524924665648.log](https://github.com/jaros1/Money-Network/files/1957790/127.0.0.1-1524924665648.log)

w2 after reload: [127.0.0.1-1524924841925.log](https://github.com/jaros1/Money-Network/files/1957791/127.0.0.1-1524924841925.log)

No W3 restore!

mn: [127.0.0.1-1524924939926.log](https://github.com/jaros1/Money-Network/files/1957793/127.0.0.1-1524924939926.log)

**Comment by jaros1** [comment]
Refactored changes in W2 to W3. Retesting import.

**Comment by jaros1** [comment]
OK full import with MN, W2 and W3. MN and W2 reloaded automatically. Had to refresh W3 manual.

![screenshot from 2018-05-02 18-28-12](https://user-images.githubusercontent.com/4932088/39536424-d0b800bc-4e36-11e8-97a2-29db6d7c6fca.png)
![screenshot from 2018-05-02 18-30-02](https://user-images.githubusercontent.com/4932088/39536449-eaf0817a-4e36-11e8-9b4d-d985ec5d6050.png)
![screenshot from 2018-05-02 18-30-46](https://user-images.githubusercontent.com/4932088/39536485-03bfdcdc-4e37-11e8-93a3-b3fbfc484738.png)

Closing issue

**Comment by jaros1** [comment]
Tested MN, W2 + W3 export and import on arch linux OK
